name: flutter_proj
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core Flutter icons
  cupertino_icons: ^1.0.8

  # Package for making API calls
  http: ^1.2.1

  # Package for getting device location
  geolocator: ^12.0.0

  # Package for handling location permissions
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linter for code analysis
  flutter_lints: ^6.0.0

  # Package for generating launcher icons
  flutter_launcher_icons: ^0.13.1

# Configuration for the flutter_launcher_icons package
# This section must have no leading spaces
flutter_launcher_icons:
  android: true
  ios: true
  # IMPORTANT: Change this path to where you saved your master icon file
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  # This section declares the assets your app will use
  assets:
    # Path to your weather GIFs
    - assets/images/
    # Path to your app icon (optional, but good practice)
    - assets/icon/

